# Generated by Django 2.0.7 on 2018-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakerlecture',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='speakerlecture',
            name='speaker_id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='speakers',
            field=models.ManyToManyField(to='INT.Speaker'),
        ),
        migrations.DeleteModel(
            name='SpeakerLecture',
        ),
    ]
