# Generated by Django 2.0.4 on 2018-06-12 17:57

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('INT', '0002_auto_20180430_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
